### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by itsZN** [pbiernat/fuckitLLVM#8]
**What is a software license?**
A software license is usually an agreement that grants a right to use software code to someone else. A license usually grants less rights than a sale of a copy of the software. The rights to use the code are defined by the terms of the license.

**Why is it important?**
Software is important; therefore software licenses are important. Today's businesses rely upon software to perform many critical functions. Software makes machines and systems work in every sector of the world economy - everything from applications that control advanced medical devices,  applications that make us entertained, applications that make companies productive, to programs that analyze the behavior of financial markets.

Software developers may want to make code available to other developers in order for applications to be more widely used in the market. Manufacturers and publishers may want to acquire rights to software that can make their products work in new ways or in ways compatible with customers' existing computer systems.

In order to have the legal right to use software to achieve the required needs, the rights and limits in the associated software license take on critical importance.

You wouldn’t want your hard-earned-my-precious-gadget get stolen, would you?

Licensing is one of the most crucial part in acquiring a software. But this is always ignored.

**Comment by Lense** [comment]
Close with https://github.com/pbiernat/fuckitLLVM/commit/7343de1e7e7bc1b83488db86897961904a46ffa0
